FinishSeed
WildCodeSchool/btz-0321-aeviso-api pull request #10
Opened 2021-06-10 12:20 UTC by ThomasBarrial

2021-06-10 13:15 UTC, Chabelle78 commented on prisma/seed.js
> +  console.log(createdCompanies);
Delete the console.log

2021-06-10 13:18 UTC, Chabelle78 requested changes
Delete the console.log

2021-06-11 07:24 UTC, Chabelle78 approved these changes

2021-06-11 07:26 UTC, Karnak19 approved these changes

2021-06-11 07:27 UTC, merged