Prisma roads
WildCodeSchool/btz-0321-aeviso-api pull request #12
Opened 2021-06-11 14:12 UTC by ThomasBarrial

2021-06-13 17:43 UTC, MatthiasWanner requested changes

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> +    res.status(500).json(err);
500 HTTP codes are using to server errors. 500 is "internal server error". Please use another code.

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> -router.get('/:id', (req, res) => {
Then/catch in /projects route, async/await in /projects/:id. I think we should choose and use same method in all the ressource.

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> +  console.log(name, description, code, companyId);
Delete the console.log when you want to merge a branch

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> +  prisma.project
Verify if required fields are in the body before requesting DB and send 400 "Bad request" if not.

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> +      res.status(500).json(err);
Not 500

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> +    res.status(500).json(err);
Not 500

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> +    console.log(err);
Delete console.log

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> +      console.log(err);
Delete console.log

2021-06-13 17:43 UTC, MatthiasWanner commented on src/api/projects.js
> +    res.status(500).json(err);
Not 500

2021-06-14 08:21 UTC, Karnak19 requested changes

2021-06-14 08:21 UTC, Karnak19 commented on src/api/projects.js
> +      res.status(404).json(err);
use async await

2021-06-14 08:45 UTC, ThomasBarrial commented on src/api/projects.js
> +      res.status(404).json(err);
Done

2021-06-14 14:28 UTC, MatthiasWanner approved these changes

2021-06-14 18:16 UTC, MatthiasWanner approved these changes

2021-06-14 18:17 UTC, merged