Routesallrecordsoneuseroneproject
WildCodeSchool/btz-0321-aeviso-api pull request #28
Opened 2021-06-21 09:15 UTC by Chabelle78

Merging routes companies, records, projects 
Delete the two previous PR corresponding to this adds

2021-06-21 10:57 UTC, Karnak19 requested changes

2021-06-21 10:57 UTC, Karnak19 commented on src/api/companies/controllers/getProjectsFromCompany.js
> +    res.status(200).json(allProjects.projects);
```js
const allProjects = await prisma.company.findUnique({
      where: { id },
    }).projects();

res.status(200).json(allProjects);
```

2021-06-21 10:57 UTC, Karnak19 commented on src/api/projects/controllers/createProjectUser.js
> +    res.sendStatus(201).json({ message: "Ok done for me projects" });
```js
res.sendStatus(204);
```

2021-06-21 10:57 UTC, Karnak19 commented on src/api/users/controllers/createUserProject.js
> +    res.sendStatus(201).json({ message: "done for me" });
```js
res.sendStatus(204);
```

2021-06-21 13:49 UTC, MatthiasWanner approved these changes

2021-06-22 07:00 UTC, Karnak19 approved these changes

2021-06-22 07:36 UTC, merged