Dev
WildCodeSchool/btz-0321-aeviso-api pull request #46
Opened 2021-07-07 07:51 UTC by MatthiasWanner

2021-07-07 16:53 UTC, Karnak19 requested changes

2021-07-07 16:53 UTC, Karnak19 commented on src/api/auth/controllers/logout.js
> +const login = (req, res, next) => {
still called login instead of logout

2021-07-07 18:08 UTC, MatthiasWanner commented on src/api/auth/controllers/logout.js
> +const login = (req, res, next) => {
Fixed in PR #51

2021-07-08 08:41 UTC, Karnak19 approved these changes

2021-07-08 08:41 UTC, merged